apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-service
spec:
  selector:
    app: complete-production-e2e-app  # This should match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80          # This is the port exposed by the service
      targetPort: 8080   # This is the container port specified in the Deployment
  type: ClusterIP  # Default service type. Change to LoadBalancer or NodePort if needed
